import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Hostel Helper</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h3 className='font-medium'>Hello Hostel Helpers!</h3>
			</main>
		</div>
	)
}
